//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleBlackjack {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleBlackjack.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be a multiple of 50. ($50, $100, $750, etc).
        /// </summary>
        public static string errorFiftyMultiplier {
            get {
                return ResourceManager.GetString("errorFiftyMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid selection. Big Cards mode selected by default..
        /// </summary>
        public static string errorGraphicModeDefault {
            get {
                return ResourceManager.GetString("errorGraphicModeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a value greater than 0.
        /// </summary>
        public static string errorNumberZero {
            get {
                return ResourceManager.GetString("errorNumberZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter only number please..
        /// </summary>
        public static string errorOnlyNumbers {
            get {
                return ResourceManager.GetString("errorOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be a multiple of 10. ($10, $20, $150, etc.).
        /// </summary>
        public static string errorTenMultiplier {
            get {
                return ResourceManager.GetString("errorTenMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot bet more than you have in your wallet..
        /// </summary>
        public static string errorTryToBetMore {
            get {
                return ResourceManager.GetString("errorTryToBetMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please only use [y|n].
        /// </summary>
        public static string errorUseYOrN {
            get {
                return ResourceManager.GetString("errorUseYOrN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Big Cards.
        /// </summary>
        public static string infoBigCards {
            get {
                return ResourceManager.GetString("infoBigCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Dealer has gone over 21. You won.
        /// </summary>
        public static string infoDealerLostWithOverTwentyOne {
            get {
                return ResourceManager.GetString("infoDealerLostWithOverTwentyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer&apos;s Turn.
        /// </summary>
        public static string infoDealerPlays {
            get {
                return ResourceManager.GetString("infoDealerPlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The dealer has more than you. You lost.
        /// </summary>
        public static string infoDealerWonWithOverPlayer {
            get {
                return ResourceManager.GetString("infoDealerWonWithOverPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        public static string infoDefault {
            get {
                return ResourceManager.GetString("infoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press [Enter] to exit....
        /// </summary>
        public static string infoExit {
            get {
                return ResourceManager.GetString("infoExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final Score.
        /// </summary>
        public static string infoFinalScore {
            get {
                return ResourceManager.GetString("infoFinalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games.
        /// </summary>
        public static string infoGames {
            get {
                return ResourceManager.GetString("infoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Both have the same score. Tie.
        /// </summary>
        public static string infoGameTie {
            get {
                return ResourceManager.GetString("infoGameTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good luck next time.
        /// </summary>
        public static string infoGoodLuck {
            get {
                return ResourceManager.GetString("infoGoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Graphic Mode.
        /// </summary>
        public static string infoGraphicModeSelect {
            get {
                return ResourceManager.GetString("infoGraphicModeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hand.
        /// </summary>
        public static string infoHand {
            get {
                return ResourceManager.GetString("infoHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game over. Press [Enter] to continue..
        /// </summary>
        public static string infoHardGameOver {
            get {
                return ResourceManager.GetString("infoHardGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lost.
        /// </summary>
        public static string infoLost {
            get {
                return ResourceManager.GetString("infoLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player&apos;s Hand.
        /// </summary>
        public static string infoPlayerHand {
            get {
                return ResourceManager.GetString("infoPlayerHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve gone over 21. You lost.
        /// </summary>
        public static string infoPlayerLostWithOverTwentyOne {
            get {
                return ResourceManager.GetString("infoPlayerLostWithOverTwentyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You got 21 with BlackJack. You won.
        /// </summary>
        public static string infoPlayerWonWithBlackjack {
            get {
                return ResourceManager.GetString("infoPlayerWonWithBlackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have more than the dealer. You won.
        /// </summary>
        public static string infoPlayerWonWithOverDealer {
            get {
                return ResourceManager.GetString("infoPlayerWonWithOverDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You reached 21. You won.
        /// </summary>
        public static string infoPlayerWonWithTwentyOne {
            get {
                return ResourceManager.GetString("infoPlayerWonWithTwentyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press [Enter] to continue.
        /// </summary>
        public static string infoPressEnterContinue {
            get {
                return ResourceManager.GetString("infoPressEnterContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select: .
        /// </summary>
        public static string infoSelect {
            get {
                return ResourceManager.GetString("infoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Short Cards.
        /// </summary>
        public static string infoShortCards {
            get {
                return ResourceManager.GetString("infoShortCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End of Game. Play again? [y|n].
        /// </summary>
        public static string infoSoftGameOver {
            get {
                return ResourceManager.GetString("infoSoftGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text.
        /// </summary>
        public static string infoText {
            get {
                return ResourceManager.GetString("infoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tied.
        /// </summary>
        public static string infoTied {
            get {
                return ResourceManager.GetString("infoTied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string infoTotal {
            get {
                return ResourceManager.GetString("infoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It must be a multiple of 50. ($50, $100, $750, etc).
        /// </summary>
        public static string infoWalletMultiplier {
            get {
                return ResourceManager.GetString("infoWalletMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Won.
        /// </summary>
        public static string infoWon {
            get {
                return ResourceManager.GetString("infoWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You lost.
        /// </summary>
        public static string infoYouLost {
            get {
                return ResourceManager.GetString("infoYouLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your wallet.
        /// </summary>
        public static string infoYourWallet {
            get {
                return ResourceManager.GetString("infoYourWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You won.
        /// </summary>
        public static string infoYouWon {
            get {
                return ResourceManager.GetString("infoYouWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language selection.
        /// </summary>
        public static string languageSelection {
            get {
                return ResourceManager.GetString("languageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It must be a multiple of 10. ($10, $20, $150, etc).
        /// </summary>
        public static string playerBetInfoTenMultiplier {
            get {
                return ResourceManager.GetString("playerBetInfoTenMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How much do you want to bet? Remaining:.
        /// </summary>
        public static string playerBetInfoWalletRemain {
            get {
                return ResourceManager.GetString("playerBetInfoWalletRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request card? [y|n].
        /// </summary>
        public static string playerCardAsk {
            get {
                return ResourceManager.GetString("playerCardAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How much money do you bring to bet?.
        /// </summary>
        public static string playerWalletAsk {
            get {
                return ResourceManager.GetString("playerWalletAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello player. Ready to play?.
        /// </summary>
        public static string playerWelcome {
            get {
                return ResourceManager.GetString("playerWelcome", resourceCulture);
            }
        }
    }
}
